/**
 * SDK generation for Programmatic Tool Calling.
 *
 * This module turns an ordered list of {@link ToolSpec}s into a self-contained,
 * runnable TypeScript SDK that lives in the tool-calling environment:
 *
 * - `dts` — a `sdk.d.ts` ambient declaration file. Every tool becomes a global
 *   async function whose argument and result types are expanded from the tool's
 *   JSON-Schema (via {@link jsonSchemaToDts}). This file doubles as the agent's
 *   documentation: it is the source of truth the type checker validates agent
 *   code against.
 * - `runtime` — an `sdk.mjs` module that installs the same functions as globals,
 *   each delegating to a single host bridge (`globalThis.__ptc`) — the
 *   "compatibility layer" that routes SDK calls to the actual tool executions.
 * - `files` — the on-disk layout of the SDK inside the in-memory environment.
 */
import { jsonSchemaToDts } from "./dts.ts";
import type { ToolSpec } from "./schema.ts";

/** A structured call result every generated SDK function resolves to. */
const CALL_RESULT_TYPE = `
  type CallResult<S> = { readonly ok: true; readonly value: S } | { readonly ok: false; readonly error: string };`;

const sanitizeName = (input: string): string => {
  if (input.length === 0) return "_";
  let out = input.replace(/[^A-Za-z0-9_$]/g, "_");
  if (/^[0-9]/.test(out)) out = `_${out}`;
  return out;
};

const typeNameOf = (tool: string, suffix: "Args" | "Result" | "Failure"): string =>
  `${sanitizeName(tool)}${suffix}`;

/**
 * Everything the SDK owns: the generated sources plus a helper to materialize
 * them into a file tree.
 */
export type SdkAssets = Readonly<{
  readonly dts: string;
  readonly runtime: string;
  /** `path -> content` layout of the SDK as it should appear in the FS. */
  readonly files: Readonly<Record<string, string>>;
}>;

/** Generate the full SDK (declarations + runtime) from tool specs. */
export const generate = (specs: ReadonlyArray<ToolSpec>): SdkAssets => {
  const typeLines: Array<string> = [];
  const functionLines: Array<string> = [];
  const runtimeLines: Array<string> = [];

  for (const spec of specs) {
    const name = sanitizeName(spec.name);

    // Expand the argument, success and failure JSON Schemas into TS types.
    typeLines.push(
      jsonSchemaToDts(spec.parametersJsonSchema, {
        rootName: typeNameOf(spec.name, "Args"),
        header: `  /** Parameters for ${spec.name}. */`,
      }),
    );
    typeLines.push(
      jsonSchemaToDts(spec.successJsonSchema, {
        rootName: typeNameOf(spec.name, "Result"),
        header: `  /** Successful result of ${spec.name}. */`,
      }),
    );
    typeLines.push(
      jsonSchemaToDts(spec.failureJsonSchema, {
        rootName: typeNameOf(spec.name, "Failure"),
        header: `  /** Failure payload of ${spec.name}. */`,
      }),
    );

    const description = spec.description
      ? `  /** ${spec.description.replace(/\*\//g, "*\\/").replace(/\n/g, " ")} */`
      : `  /** ${spec.name} tool. */`;
    functionLines.push(
      description,
      `  function ${name}(args: ${typeNameOf(spec.name, "Args")}): Promise<CallResult<${typeNameOf(
        spec.name,
        "Result",
      )}>>;`,
    );

    runtimeLines.push(`function ${name}(args) { return call("${spec.name}", args); }`);
    runtimeLines.push(`globalThis.${name} = ${name};`);
  }

  const header = [
    "/* AUTO-GENERATED by @open-insight/agent PTC. Do not edit by hand. */",
    "",
    "// Script contract: declare a single `async function main()`. Call the tool",
    "// globals below with `await` and inspect `r.ok` / `r.value` / `r.error`, then",
    "// `return` the result. The runner invokes `main()`; its resolved value is the",
    "// program result and console.log output is captured as stdout.",
  ].join("\n");

  const hostGlobals = [
    "",
    "  /** Console captured by the runner into the run result. */",
    "  var console: {",
    "    log: (...args: Array<unknown>) => void;",
    "    info: (...args: Array<unknown>) => void;",
    "    warn: (...args: Array<unknown>) => void;",
    "    error: (...args: Array<unknown>) => void;",
    "  };",
  ].join("\n");

  const dts = [
    header,
    "declare global {",
    CALL_RESULT_TYPE.trimStart(),
    ...typeLines.map((line) => line.replace(/^export /, "  ")),
    ...functionLines.map((line) =>
      line.startsWith("  ") || line.startsWith("/") ? line : `  ${line}`,
    ),
    hostGlobals.trimStart(),
    "}",
    "export {};",
    "",
  ].join("\n");

  const runtime = [header, "const call = globalThis.__ptc;", ...runtimeLines, ""].join("\n");

  return {
    dts,
    runtime,
    files: {
      "sdk.d.ts": dts,
      "sdk.mjs": runtime,
    },
  };
};
