/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as McpRouteImport } from "./routes/mcp";
import { Route as EventRouteImport } from "./routes/event";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DemoTableRouteImport } from "./routes/demo/table";
import { Route as DemoMcpTodosRouteImport } from "./routes/demo/mcp-todos";
import { Route as DemoApiMcpTodosRouteImport } from "./routes/demo/api.mcp-todos";

const McpRoute = McpRouteImport.update({
  id: "/mcp",
  path: "/mcp",
  getParentRoute: () => rootRouteImport,
} as any);
const EventRoute = EventRouteImport.update({
  id: "/event",
  path: "/event",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DemoTableRoute = DemoTableRouteImport.update({
  id: "/demo/table",
  path: "/demo/table",
  getParentRoute: () => rootRouteImport,
} as any);
const DemoMcpTodosRoute = DemoMcpTodosRouteImport.update({
  id: "/demo/mcp-todos",
  path: "/demo/mcp-todos",
  getParentRoute: () => rootRouteImport,
} as any);
const DemoApiMcpTodosRoute = DemoApiMcpTodosRouteImport.update({
  id: "/demo/api/mcp-todos",
  path: "/demo/api/mcp-todos",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/event": typeof EventRoute;
  "/mcp": typeof McpRoute;
  "/demo/mcp-todos": typeof DemoMcpTodosRoute;
  "/demo/table": typeof DemoTableRoute;
  "/demo/api/mcp-todos": typeof DemoApiMcpTodosRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/event": typeof EventRoute;
  "/mcp": typeof McpRoute;
  "/demo/mcp-todos": typeof DemoMcpTodosRoute;
  "/demo/table": typeof DemoTableRoute;
  "/demo/api/mcp-todos": typeof DemoApiMcpTodosRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/event": typeof EventRoute;
  "/mcp": typeof McpRoute;
  "/demo/mcp-todos": typeof DemoMcpTodosRoute;
  "/demo/table": typeof DemoTableRoute;
  "/demo/api/mcp-todos": typeof DemoApiMcpTodosRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/about"
    | "/event"
    | "/mcp"
    | "/demo/mcp-todos"
    | "/demo/table"
    | "/demo/api/mcp-todos";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/about"
    | "/event"
    | "/mcp"
    | "/demo/mcp-todos"
    | "/demo/table"
    | "/demo/api/mcp-todos";
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/event"
    | "/mcp"
    | "/demo/mcp-todos"
    | "/demo/table"
    | "/demo/api/mcp-todos";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  EventRoute: typeof EventRoute;
  McpRoute: typeof McpRoute;
  DemoMcpTodosRoute: typeof DemoMcpTodosRoute;
  DemoTableRoute: typeof DemoTableRoute;
  DemoApiMcpTodosRoute: typeof DemoApiMcpTodosRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/mcp": {
      id: "/mcp";
      path: "/mcp";
      fullPath: "/mcp";
      preLoaderRoute: typeof McpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/event": {
      id: "/event";
      path: "/event";
      fullPath: "/event";
      preLoaderRoute: typeof EventRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/demo/table": {
      id: "/demo/table";
      path: "/demo/table";
      fullPath: "/demo/table";
      preLoaderRoute: typeof DemoTableRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/demo/mcp-todos": {
      id: "/demo/mcp-todos";
      path: "/demo/mcp-todos";
      fullPath: "/demo/mcp-todos";
      preLoaderRoute: typeof DemoMcpTodosRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/demo/api/mcp-todos": {
      id: "/demo/api/mcp-todos";
      path: "/demo/api/mcp-todos";
      fullPath: "/demo/api/mcp-todos";
      preLoaderRoute: typeof DemoApiMcpTodosRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EventRoute: EventRoute,
  McpRoute: McpRoute,
  DemoMcpTodosRoute: DemoMcpTodosRoute,
  DemoTableRoute: DemoTableRoute,
  DemoApiMcpTodosRoute: DemoApiMcpTodosRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
