import type { Prompt } from "@open-insight/core/internal";
import { Effect, Schema } from "effect";
import { Response, Tool } from "effect/unstable/ai";

export type State = Readonly<{
  trajectory: Prompt.Trajectory;
  responding: Array<Prompt.Part>;
}>;

type ToolCallInput<Tools extends Record<string, Tool.Any>> = Readonly<{
  state: State;
  call: Response.ToolCallParts<Tools>;
  /**
   * Original tool result generated by the given toolkit.
   */
  result: Response.ToolResultParts<Tools>;
}>;

type ToolCallOutput<Tools extends Record<string, Tool.Any>> = Readonly<{
  state: State;
  /**
   * Actual tool result that will be used in the next prompting.
   */
  result: Response.ToolResultParts<Tools>;
}>;

export type ToolCallFn<Tools extends Record<string, Tool.Any>> = (
  input: ToolCallInput<Tools>,
) => Effect.Effect<ToolCallOutput<Tools>>;

type PromptInput = Readonly<{
  state: State;
  /**
   * Original prompt that will be used to generate the next response.
   */
  prompt: Prompt.Prompt;
}>;

type PromptOutput = Readonly<{
  state: State;
  /**
   * Actual prompt that will be used to generate the next response.
   */
  prompt: Prompt.Prompt;
}>;

export type PromptFn = (input: PromptInput) => Effect.Effect<PromptOutput>;

export type Input = Readonly<{
  state: State;
  reason: Response.FinishReason;
}>;
export type Output = State;
export type AnyFn = (input: Input) => Effect.Effect<Output>;

export class Metadata extends Schema.Class<Metadata>("Metadata")({
  name: Schema.String,
  description: Schema.optional(Schema.String),
}) {}
export type MetadataEncoded = Schema.Codec.Encoded<typeof Metadata>;

export type Middleware = Readonly<{
  metadata: Metadata;
  fn: Fn;
}>;

type Options = MetadataEncoded;

export const make = Effect.fn(function* (fn: Fn, options: Options) {
  const metadata = yield* Schema.decodeEffect(Metadata)(options);
  return { metadata, fn } as Middleware;
});
